media:
  - name: images
    label: Images
    input: media/images
    output: /media/images
    categories:
      - image

  - name: documents
    label: Documents
    input: media/documents
    output: /media/documents
    categories:
      - document

content:
  # ─────────────────────────────────────────
  # AUTHORS
  # ─────────────────────────────────────────

  - name: authors
    label: Authors
    type: collection
    path: content/authors
    view:
      primary: name

    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: bio
        label: Biography
        type: text

      - name: avatar
        label: Avatar
        type: image
        options:
          media: images

      - name: website
        label: Website
        type: string

  # ─────────────────────────────────────────
  # CATEGORIES
  # ─────────────────────────────────────────

  - name: categories
    label: Categories
    type: collection
    path: content/categories
    view:
      primary: name

    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: image
        label: Image
        type: image
        options:
          media: images

  # ─────────────────────────────────────────
  # ARTICLES
  # ─────────────────────────────────────────

  - name: articles
    label: Articles
    type: collection
    path: content/articles
    view:
      primary: title
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: image
        label: Featured Image
        type: image
        options:
          media: images

      - name: description
        label: Description
        type: text

      - name: author
        label: Author
        type: reference

        options:
          collection: authors
          value: "{path}"
          label: "{primary}"

      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          min: 1
          max: 5
          value: "{path}"
          label: "{primary}"

      - name: related
        label: Related Articles
        type: reference
        options:
          collection: articles
          multiple: true
          max: 4
          value: "{path}"
          label: "{primary}"

      - name: date
        label: Published Date
        type: date

      - name: tags
        label: Tags
        type: string
        list: true

      - name: status
        label: Status
        type: select
        options:
          values:
            - draft
            - published
            - archived

      - name: body
        label: Content
        type: rich-text
        options:
          format: markdown
          media: images
