media: media

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: text

      - name: date
        label: Published Date
        type: date

      - name: tags
        label: Tags
        type: string
        list: true

      - name: status
        label: Status
        type: select
        options:
          values:
            - draft
            - published
            - archived

      - name: body
        label: Content
        type: rich-text
        options:
          format: markdown
